# GET http://localhost:4200/api/getproducts
# Content-Type: application/json
# Accept: application/json



# POST http://localhost:4200/api/updateproducts
# Content-Type: application/json
# Accept: application/json



# [
# {
#   "_id": "699c3f3888ebf6a5bca45bc3",
#   "name": "Wear The Code Mug with Picture",
#   "slug": "wear-the-code-sticker-blue3325641",
#   "desc": "tbhgf",
#   "img": "https://m.media-amazon.com/images/I/61zIgT7uE6L._SY741_.jpg",
#   "category": "sticker",
#   "size": "L",
#   "color": "Dark Blue",
#   "price": 599,
#   "availableQty": 5
# }
# ]








# POST http://localhost:4200/api/addproducts
# Content-Type: application/json
# Accept: application/json
 
#  [
#   {
#     "name": "Wear The Code Sticker Pack Square",
#     "slug": "wear-the-code-sticker-pack-square-random1",
#     "desc": "tbhgf",
#     "img": "https://m.media-amazon.com/images/I/813o6C7QH2L._SX679_.jpg",
#     "category": "stickers",
#     "color": "Random 1",
#     "price": 99,
#     "availableQty": 5
#    },
#    {
#     "name": "Wear The Code Sticker Pack Square",
#     "slug": "wear-the-code-sticker-pack-square-paper",
#     "desc": "tbhgf",
#     "img": "https://m.media-amazon.com/images/I/71KjxcygPJL._SX679_.jpg",
#     "category": "stickers",
#     "color": "Paper",
#     "price": 99,
#     "availableQty": 5
#    },
#    {
#     "name": "Wear The Code Sticker Pack Square",
#     "slug": "wear-the-code-sticker-pack-square-job",
#     "desc": "tbhgf",
#     "img": "https://m.media-amazon.com/images/I/71sbuejOUyL._SX679_.jpg",
#     "category": "sticker",
#     "color": "Job",
#     "price": 99,
#     "availableQty": 5
#    },
#    {
#     "name": "Wear The Code Sticker Pack Square",
#     "slug": "wear-the-code-sticker-pack-square-super-hero",
#     "desc": "tbhgf",
#     "img": "https://m.media-amazon.com/images/I/91KThPLK+JL._SX679_.jpg",
#     "category": "stickers",
#     "color": "Super Hero",
#     "price": 99,
#     "availableQty": 5
#    },
#    {
#     "name": "Wear The Code Sticker Pack Square",
#     "slug": "wear-the-code-sticker-pack-square-business",
#     "desc": "tbhgf",
#     "img": "https://m.media-amazon.com/images/I/71+IkzKc0ZL._SX679_.jpg",
#     "category": "stickers",
#     "color": "Business",
#     "price": 99,
#     "availableQty": 5
#    },
#    {
#     "name": "Wear The Code Sticker Pack Square",
#     "slug": "wear-the-code-sticker-pack-square-tourist-places",
#     "desc": "tbhgf",
#     "img": "https://m.media-amazon.com/images/I/91vMdMQ6HlL._SX679_.jpg",
#     "category": "stickers",
#     "color": "Tourist Places",
#     "price": 99,
#     "availableQty": 5
#   },
#   {
#     "name": "Wear The Code Sticker Pack Square",
#     "slug": "wear-the-code-sticker-pack-square-random2",
#     "desc": "tbhgf",
#     "img": "https://m.media-amazon.com/images/I/71yV7GzCQML._SX679_.jpg",
#     "category": "stickers",
#     "color": "Random 2",
#     "price": 99,
#     "availableQty": 5
#   },
#   {
#     "name": "Wear The Code Sticker Pack Square",
#     "slug": "wear-the-code-sticker-pack-square-pets",
#     "desc": "tbhgf",
#     "img": "https://m.media-amazon.com/images/I/716ENVdmt4L._SX679_.jpg",
#     "category": "stickers",
#     "color": "Pets",
#     "price": 99,
#     "availableQty": 5
#   }
# ]