



POST http://localhost:4200/api/posttransaction
Content-Type: application/json
Accept: application/json

{
  "oid": 395475277368,
  "cart": {
    "wear-the-code-sticker-pack-square-super-hero": {
      "qty": 33,
      "price": 1000,
      "name": "Wear The Code Sticker Pack Square",
      "size": "undefined",
      "variant": "Super Hero"
    }
  },
  "subTotal": 1,
  "razorpay_payment_id": "pay_ST4ONLkmntwTBZ",
  "razorpay_order_id": "order_ST4Nr05N2yZjxv",
  "razorpay_signature": "6a5466daa76be0a6426d5bf896e825f96be40469a5ae0f40767e7c3fe01262f5"
}
